### ISSUE TITLE
i have to work on this package raise some error and not create bin and lib folder

### ISSUE THREAD

**Issue by venkatsudheer** [holtwick/pyxer#1]
xpaster serve
Paster
Init virtualenv /home/tnkiton-g510-001/Videos/MyExample12
Running command /home/tnkiton-g510-001/Videos/MyExample12/bin/paster serve /home/tnkiton-g510-001/Videos/MyExample12/development.ini 
error [Errno 2] No such file or directory
ERROR [pyxer.utils] /usr/lib/python2.7/site-packages/pyxer/utils/__init__.py line 157: Error while executing command '/home/tnkiton-g510-001/Videos/MyExample12/bin/paster serve /home/tnkiton-g510-001/Videos/MyExample12/development.ini '
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyxer/utils/__init__.py", line 154, in call_subprocess
    env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by holtwick** [comment]
I'm sorry, the project is discontinued :(

**Comment by venkatsudheer** [comment]
ok  thanks
