### ISSUE TITLE
Unable To Run The Myexample

### ISSUE THREAD

**Issue by Mayur700** [holtwick/pyxer#2]
Hello Holtwick.

I have tried using your library as you documented on my centos machine whenever I run **pyxer init myExample**  , I get the following error. Please help me in sorting out the error.

**<<<<<<<<<<<<<<<<<< The error is >>>>>>>>>>>>>>>>>>>**.
[satya@localhost JackRabbitTutorials]$ pyxer init myExample
Google AppEngine
Running command easy_install-2.5 -a -Z -d /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages -s /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/.hidden-bin -U paste
ERROR [pyxer.utils] /usr/lib/python2.7/site-packages/pyxer-0.7.2-py2.7.egg/pyxer/utils/__init__.py line 156: Error while executing command 'easy_install-2.5 -a -Z -d /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages -s /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/.hidden-bin -U paste'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyxer-0.7.2-py2.7.egg/pyxer/utils/__init__.py", line 154, in call_subprocess
    env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Running command easy_install-2.5 -a -Z -d /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages -s /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/.hidden-bin -U setuptools
ERROR [pyxer.utils] /usr/lib/python2.7/site-packages/pyxer-0.7.2-py2.7.egg/pyxer/utils/__init__.py line 156: Error while executing command 'easy_install-2.5 -a -Z -d /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages -s /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/.hidden-bin -U setuptools'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyxer-0.7.2-py2.7.egg/pyxer/utils/__init__.py", line 154, in call_subprocess
    env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Running command easy_install-2.5 -a -Z -d /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages -s /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/.hidden-bin -U beaker
ERROR [pyxer.utils] /usr/lib/python2.7/site-packages/pyxer-0.7.2-py2.7.egg/pyxer/utils/__init__.py line 156: Error while executing command 'easy_install-2.5 -a -Z -d /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages -s /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/.hidden-bin -U beaker'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyxer-0.7.2-py2.7.egg/pyxer/utils/__init__.py", line 154, in call_subprocess
    env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/command.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/utils/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/utils/jsonhelper.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/routing.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/controller.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/base.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/helpers.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/recaptcha/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/sling/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/sling/sling.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/gae/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/path.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/output.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/util.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/filters/transform.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/filters/i18n.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/filters/html.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/filters/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/core.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/input.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/genshi/builder.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/cssselect.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/template/templatestream.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/paster/__init__.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/create.py
create /home/satya/MyWorkSpace/JackRabbitTutorials/myExample/site-packages/pyxer/app.py
Initialization completed!
[satya@localhost JackRabbitTutorials]$ ^C
[satya@localhost JackRabbitTutorials]$

**Comment by holtwick** [comment]
The project is discontinued.
